input InviteUserInput {
  email: String!
  firstName: String
  lastName: String
}

input CreateBoardInput {
  title: String!
  description: String
}

type Mutation {
  inviteUser(input: InviteUserInput): User

  createBoard(input: CreateBoardInput): Board
  inviteBoardMember(boardId: ID!, invite: InviteUserInput): Board
}
